apiVersion: v1
kind: ConfigMap
metadata:
  name: cfgmap-values
  namespace: homework
data:
  given: Andrey
  family: Ni
  village: Likovo
  age: "33"
  state: SU
  year: "2025"
  month: "8"
  day: "40"
  hour: "25"