apiVersion: v1
clusters:
- cluster:
    certificate-authority: C:\Users\user\.minikube\ca.crt
    extensions:
    - extension:
        last-update: Sat, 28 Sep 2024 14:53:11 MSK
        provider: minikube.sigs.k8s.io
        version: v1.33.1
      name: cluster_info
    server: https://192.168.59.101:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    namespace: homework
    user: cd
  name: cd
current-context: cd
kind: Config
preferences: {}
users:
- name: cd
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IktMWDJhTG9sOC11VEFFYnFkdHk5Ul9yMUZ6aDVuUVc0anNyYUd4SlpKM2cifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzI3NjIyMzY3LCJpYXQiOjE3Mjc1MzU5NjcsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiODU0ODljYmMtM2M0My00NGE0LWE4ZjUtZTI5NmRmMTA5ZTJiIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJob21ld29yayIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJjZCIsInVpZCI6ImY4MzhmNzQ2LTcwNjYtNGYzNS04ZmZlLTFmMzBiM2IyZDU5YSJ9fSwibmJmIjoxNzI3NTM1OTY3LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6aG9tZXdvcms6Y2QifQ.k5bHJCghMyVD8Rrl4-u8KixG915ogIgojKpYEgS8TDMTyCkc3_Hl1zbQAfJRJO_SzYap4PM-cfFmS257hR9_xqkwxHzLxoUAEQM87vuYwqng1AV4eVQcyiMgcTS_XE_FOBoNoJBYEOFb_5P0oLBzUL-yfy3gOzRY6cpYW9zkT1PHsbfO3tqBtht5USq08tkROJGAGW6nZ5yfxYHtboB0EwbCO20SDffFtCcMWjW6UCFGBv9O1HsfuIYwWKCCk-gtvmUfR855JUx-t2iUEN9rc7lNvQiq5eR8dCmCnnDwBZ5iEeVCukcCJPGoHtbIZ67VEru5iW8zxsRMpwzu47sETw
