apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-default
  namespace: homework
spec:
  selector:
  storageClassName: "sc-hostpath"
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Mi